// JavaScript Document
function vgmForm(request, response) {
    if (request.getMethod() == 'GET') {
        var recId = request.getParameter('recName');
        var logoURL = 'http://static1.squarespace.com/static/59c5ae06f6576e0477afe509/59c65927f43b55ff86b5eaef/59c6abde8419c269b81ca801/1506279268039/?format=1500w';
        var record = nlapiLoadRecord('customrecord_h5_shipment', recId, null, null);
        var recNum = record.getFieldValue('name');
        var recNumTrimmed = recNum.substr(10, 7);
        var emp = record.getFieldValue('custrecord_h5_custservteamlead');
        var empText = record.getFieldText('custrecord_h5_custservteamlead');
        var empEmail = nlapiLookupField('employee',emp,'email');
        var weightUOM = record.getFieldText('custrecord_h5_weight_uom');
        var vgmMethod = record.getFieldText('custrecord_h5_vgmmethod');
        var carrierText = record.getFieldText('custrecord_h5_carrier');
        var shipDate = record.getFieldValue('custrecord_h5_ship_date');
        var refatpickup = record.getFieldValue('custrecord_h5_reference_pickup');
        var shipType = record.getFieldText('custrecord_h5_shipment_type');
        var customsBroker = record.getFieldValue('custrecord_h5_customsbroker');
        var bookingNum = record.getFieldValue('custrecord_h5_intlbookingnum');
        var portOfEntry = record.getFieldValue('custrecord_h5_portofentry');
        if (portOfEntry === null){portOfEntry = '';}
        var refatdelivery = record.getFieldValue('custrecord_h5_reference_delivery');
        var customsInstructions = record.getFieldValue('custrecord_h5_customs_instructions');
        if (customsInstructions === null){customsInstructions = '';}
        var shipperAddressee = record.getFieldValue('custrecord_h5_shipper_addressee');
        var shipperAddr1 = record.getFieldValue('custrecord_h5_shipper_addr_1');
        var shipperAddr2 = record.getFieldValue('custrecord_h5_shipper_addr_2');
        if (shipperAddr2 === null){shipperAddr2 = '';}
        var shipperCity = record.getFieldValue('custrecord_h5_shipper_city');
        var shipperState = record.getFieldValue('custrecord_h5_shipper_state');
        var shipperZip = record.getFieldValue('custrecord_h5_shipper_zip');
        var shipperCountry = record.getFieldValue('custrecord_h5_shipper_country');
        var consigneeAddressee = record.getFieldValue('custrecord_h5_consignee_addree');
        var consigneeAddr1 = record.getFieldValue('custrecord_h5_consignee_addr1');
        var consigneeAddr2 = record.getFieldValue('custrecord_h5_consignee_addr2');
        if (consigneeAddr2 === null){consigneeAddr2 = '';}
        var consigneeCity = record.getFieldValue('custrecord_h5_consignee_city');
        var consigneeState = record.getFieldValue('custrecord_h5_consignee_state');
        var consigneeZip = record.getFieldValue('custrecord_h5_consignee_zip');
        var consigneeCountry = record.getFieldValue('custrecord_h5_consignee_country');
        var linHazmat = new Array();
        var linPicCount = new Array();
        var linType = new Array();
        var linNum = new Array();
        var linDesc = new Array();
        var linHTS = new Array();
        var linWeight = new Array();
        var linUnitPrice = new Array();
        var linExtendedTotal = new Array();
        var items = new Array();
        var totLPC = 0;
        var totLPic = 0;
        var totInvUnit = 0;
        var totWeight = 0;
        var totAmount = 0;
        var pkgcount = new Array();
        var fil = new Array();
        fil[0] = new nlobjSearchFilter('custrecord_h5_shipment_parent', null, 'is', recId);
        var col = new Array();
        col[0] = new nlobjSearchColumn('custrecord_h5_pkgnumber');
        col[1] = new nlobjSearchColumn('custrecord_h5_piece_count');
        col[2] = new nlobjSearchColumn('custrecord_h5_ship_line_item_desc');
        col[3] = new nlobjSearchColumn('custrecord_h5_packagetype');
        col[4] = new nlobjSearchColumn('custrecord_h5_weight');
        col[5] = new nlobjSearchColumn('custrecord_h5_unitprice');
        col[6] = new nlobjSearchColumn('custrecord_h5_extendedtotal');
        col[7] = new nlobjSearchColumn('custrecord_h5_inventoryunits');
        var packages = nlapiSearchRecord('customrecord_h5_shipment_line', null, fil, col);
        for (var x = 0; x < packages.length; x++) {
            pkgcount.push(packages[x].getValue('custrecord_h5_pkgnumber'));
            var linPicCount = packages[x].getValue('custrecord_h5_piece_count');
            var linInventoryUnits = packages[x].getValue('custrecord_h5_inventoryunits');
            var linHTS = packages[x].getValue('custrecord_h5_htsnumber');
            var linDesc = packages[x].getValue('custrecord_h5_ship_line_item_desc');
            var linType = packages[x].getText('custrecord_h5_packagetype');
            var linWeight = packages[x].getValue('custrecord_h5_weight');
            var linNum = packages[x].getValue('custrecord_h5_pkgnumber');
            var linUnitPrice = packages[x].getValue('custrecord_h5_unitprice');
            var linExtendedTotal = packages[x].getValue('custrecord_h5_extendedtotal');
            totLPic += Number(linPicCount);
            totInvUnit += Number(linInventoryUnits);
            totWeight += Number(linWeight);
            totAmount += Number(linExtendedTotal);
            //var totAmountDisplay = AddCommas(totAmount);

            items += '<tr>';
            items += '<td align="left" style="border-top-style:solid;border-top-width:.5pt;border-left-style:solid;border-left-width:.5pt;border-bottom-style:solid;border-bottom-width:.5pt;border-right-style:solid;border-right-width:.5pt" colspan="1" rowspan="1"><p class="s2" style="padding-top: 2pt;padding-left: 2pt">' + linDesc +'</p></td>';
            items += '<td align="right" style="border-top-style:solid;border-top-width:.5pt;border-left-style:solid;border-left-width:.5pt;border-bottom-style:solid;border-bottom-width:.5pt;border-right-style:solid;border-right-width:.5pt" colspan="1" rowspan="1"><p class="s2" style="padding-top: 2pt">' + linInventoryUnits +'</p></td>';
            items += '<td align="right" style="border-top-style:solid;border-top-width:.5pt;border-left-style:solid;border-left-width:.5pt;border-bottom-style:solid;border-bottom-width:.5pt;border-right-style:solid;border-right-width:.5pt" colspan="1" rowspan="1"><p class="s2" style="padding-top: 2pt">' + linUnitPrice +'</p></td>';
            items += '<td align="right" style="border-top-style:solid;border-top-width:.5pt;border-left-style:solid;border-left-width:.5pt;border-bottom-style:solid;border-bottom-width:.5pt;border-right-style:solid;border-right-width:.5pt" colspan="1" rowspan="1"><p class="s2" style="padding-top: 2pt">' + AddCommas(Math.round(linExtendedTotal)) +'</p></td></tr>';
          }

        var pkgcnt = Math.max.apply(null, pkgcount);
        var totWeightkg = Math.round((totWeight / 2.2046226218));
        var hotTots = '<tr><td>Total Package Count:' + '</td><td>' + pkgcnt + '</td><td>' + '' + '</td><td>' + '' + '</td><td>' + '' + '</td><td>' + 'Total Weight:' + '</td><td>' + totWeight + 'lbs' + '</td></tr>';
        nlapiLogExecution('DEBUG', 'Line Item Count', 'lines array: ' + items + '');
        //begin template well formed XML - ajr
        try {
          var xml = '<?xml version=\"1.0\"?>\n<!DOCTYPE pdf PUBLIC \"-//big.faceless.org//report\" \"report-1.1.dtd\">\n';
          xml += '<pdf>';
          xml += '<link name="verdana" type="font" subtype="opentype" src="${nsfont.verdana}" src-bold="${nsfont.verdana_bold}" bytes="2" />';
          xml += '<head>';
          xml += '<meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>';
          xml += '<meta name="title" value="Customs Declaration"/>';
          xml += '<meta name="layout" value="single-page"/>';
          xml += '<style type="text/css"> * {margin:0; padding:0; text-indent:0; }';
          xml += 'h2 { color: black; font-family:Arial, sans-serif; font-style: normal; font-weight: bold; font-size: 9pt; }';
          xml += 'p { color: black; font-family:Arial, sans-serif; font-style: normal; font-weight: normal; font-size: 7pt; margin:0pt; }';
          xml += 'h1 { color: black; font-family:Arial, sans-serif; font-style: normal; font-weight: bold; font-size: 13pt; }';
          xml += 'a { color: #00F; font-family:Arial, sans-serif; font-style: normal; font-weight: normal; text-decoration: underline; font-size: 7pt; }';
          xml += '.s1 { color: black; font-family:Arial, sans-serif; font-style: normal; font-weight: normal; font-size: 5pt; }';
          xml += '.s2 { color: black; font-family:Arial, sans-serif; font-style: normal; font-weight: normal; font-size: 7pt; }';
          xml += '.s3 { color: black; font-family:Arial, sans-serif; font-style: normal; font-weight: bold; font-size: 9pt; }';
          xml += '.s4 { color: black; font-family:Arial, sans-serif; font-style: normal; font-weight: normal; font-size: 12pt; }';
          xml += '.s5 { color: black; font-family:Arial, sans-serif; font-style: normal; font-weight: bold; font-size: 14pt; }';
          xml += '.s6 { color: black; font-family:Arial, sans-serif; font-style: normal; font-weight: normal; font-size: 6pt; vertical-align: -2pt; }';
          xml += '.s7 { color: black; font-family:Arial, sans-serif; font-style: normal; font-weight: normal; font-size: 10pt; }';
          xml += '.s8 { color: black; font-family:"Times New Roman", serif; font-style: normal; font-weight: normal; font-size: 10pt; }';
          xml += '.s9 { color: black; font-family:"Times New Roman", serif; font-style: normal; font-weight: normal; font-size: 6pt; }';
          xml += '.s10 { color: black; font-family:Wingdings; font-style: normal; font-weight: normal; font-size: 10pt; }';
          xml += '.s12 { color: black; font-family:Arial, sans-serif; font-style: normal; font-weight: bold; font-size: 8pt; }';
          xml += '.s13 { color: black; font-family:Arial, sans-serif; font-style: normal; font-weight: bold; font-size: 7pt; }';
          xml += '.s14 { color: black; font-family:Arial, sans-serif; font-style: normal; font-weight: normal; font-size: 8pt; }';
          xml += '.s16 { color: black; font-family:Arial, sans-serif; font-style: normal; font-weight: lighter; font-size: 8pt; }';
          xml += '.s17 { color: black; font-family:Arial, sans-serif; font-style: normal; font-weight: normal; font-size: 6pt; }';
          xml += '</style>';
          xml += '</head>';
          xml += '<body size="letter" margin="0.15in">';

          xml += '<table width="500" style="border-collapse:collapse;margin-left:6.00pt" cellspacing="0"><tr><td align="top"><img src="' + logoURL + '" height="42" width="42"/></td><td></td><td></td>';
          xml += '<td style="padding-top: 15pt;padding-left: 2pt"><p class="s5">Verified Gross Mass (VGM) Declaration Form</p></td></tr></table>';

          xml += '<table width="500" style="border-collapse:collapse;margin-left:6.00pt" cellspacing="0">';
          xml += '<tr style="width=100%;height:17pt">';
          xml += '<td style="background-color: lightgrey;border-top-style:solid;border-top-width:1pt;border-left-style:solid;border-left-width:1pt;border-bottom-style:solid;border-bottom-width:0pt;border-right-style:solid;border-right-width:0pt" width="40%">';
          xml += '<p class="s3" style="padding-top: 0pt;padding-left: 5pt;text-indent: 0pt;text-align: left;">Date</p>';
          xml += '</td>';
          xml += '<td style="border-top-style:solid;border-top-width:1pt;border-left-style:solid;border-left-width:1pt;border-bottom-style:solid;border-bottom-width:0pt;border-right-style:solid;border-right-width:1pt" width="60%">';
          xml += '<p class="s4" style="padding-top: 2pt;padding-left: 2pt;text-indent: 0pt;text-align: left;">' + shipDate +'</p>';
          xml += '</td>';
          xml += '</tr>';
          xml += '<tr style="width=100%;height:17pt">';
          xml += '<td style="background-color: lightgrey;border-top-style:solid;border-top-width:1pt;border-left-style:solid;border-left-width:1pt;border-bottom-style:solid;border-bottom-width:0pt;border-right-style:solid;border-right-width:0pt" colspan="1">';
          xml += '<p class="s4" style="padding-top: 2pt;padding-left: 5pt;text-indent: 0pt;text-align: left;">Shipper Information:</p>';
          xml += '<p class="s4" style="padding-top: 2pt;padding-left: 5pt;text-indent: 0pt;text-align: left;">Company Name</p>';
          xml += '<p class="s4" style="padding-top: 2pt;padding-left: 5pt;text-indent: 0pt;text-align: left;">Authorized Personnel</p>';
          xml += '<p class="s4" style="padding-top: 2pt;padding-left: 5pt;text-indent: 0pt;text-align: left;">Contact Phone</p>';
          xml += '<p class="s4" style="padding-top: 2pt;padding-left: 5pt;text-indent: 0pt;text-align: left;">Contact Email</p>';
          xml += '</td>';
          xml += '<td style="border-top-style:solid;border-top-width:1pt;border-left-style:solid;border-left-width:1pt;border-bottom-style:solid;border-bottom-width:0pt;border-right-style:solid;border-right-width:1pt" colspan="1">';
          xml += '<p class="s4" style="padding-top: 2pt;padding-left: 2pt;text-indent: 0pt;text-align: left;"><br /></p>';
          xml += '<p class="s4" style="padding-top: 2pt;padding-left: 2pt;text-indent: 0pt;text-align: left;">Pliteq Inc.</p>';
          xml += '<p class="s4" style="padding-top: 2pt;padding-left: 2pt;text-indent: 0pt;text-align: left;">' + empText +'</p>';
          xml += '<p class="s4" style="padding-top: 2pt;padding-left: 2pt;text-indent: 0pt;text-align: left;">416-775-5380</p>';
          xml += '<p class="s4" style="padding-top: 2pt;padding-left: 2pt;text-indent: 0pt;text-align: left;">' + empEmail +'</p>';
          xml += '</td>';
          xml += '</tr>';
          xml += '<tr style="width=100%;height:17pt">';
          xml += '<td style="background-color: lightgrey;border-top-style:solid;border-top-width:1pt;border-left-style:solid;border-left-width:1pt;border-bottom-style:solid;border-bottom-width:0pt;border-right-style:solid;border-right-width:0pt" colspan="1">';
          xml += '<p class="s4" style="padding-top: 0pt;padding-left: 5pt;text-indent: 0pt;text-align: left;">Shipment Reference #</p>';
          xml += '</td>';
          xml += '<td style="border-top-style:solid;border-top-width:1pt;border-left-style:solid;border-left-width:1pt;border-bottom-style:solid;border-bottom-width:0pt;border-right-style:solid;border-right-width:1pt" colspan="1">';
          xml += '<p class="s4" style="padding-top: 2pt;padding-left: 2pt;text-indent: 0pt;text-align: left;">' + recNum +'</p>';
          xml += '</td>';
          xml += '</tr>';
          xml += '<tr style="width=100%;height:17pt">';
          xml += '<td style="background-color: lightgrey;border-top-style:solid;border-top-width:1pt;border-left-style:solid;border-left-width:1pt;border-bottom-style:solid;border-bottom-width:0pt;border-right-style:solid;border-right-width:0pt" colspan="1">';
          xml += '<p class="s4" style="padding-top: 0pt;padding-left: 5pt;text-indent: 0pt;text-align: left;">Shipment Type</p>';
          xml += '</td>';
          xml += '<td style="border-top-style:solid;border-top-width:1pt;border-left-style:solid;border-left-width:1pt;border-bottom-style:solid;border-bottom-width:0pt;border-right-style:solid;border-right-width:1pt" colspan="1">';
          xml += '<p class="s5" style="padding-top: 2pt;padding-left: 2pt;text-indent: 0pt;text-align: left;">' + shipType +'</p>';
          xml += '</td>';
          xml += '</tr>';
          xml += '<tr style="width=100%;height:17pt">';
          xml += '<td style="background-color: lightgrey;border-top-style:solid;border-top-width:1pt;border-left-style:solid;border-left-width:1pt;border-bottom-style:solid;border-bottom-width:0pt;border-right-style:solid;border-right-width:0pt" colspan="1">';
          xml += '<p class="s2" style="padding-top: 0pt;padding-left: 5pt;text-indent: 0pt;text-align: left;">Method for Deriving the Weight</p>';
          xml += '<p class="s2" style="padding-top: 0pt;padding-left: 5pt;text-indent: 0pt;text-align: left;"><u>Actual:</u> Where the weight was derived by weighing the packed and sealed container.</p>';
          xml += '<p class="s2" style="padding-top: 0pt;padding-left: 5pt;text-indent: 0pt;text-align: left;"><u>Calculated:</u> Where the weight was derived by adding the weight of the packages and cargo items including pallets, dunnage, etc. to the tare weight of the container.</p>';
          xml += '</td>';
          xml += '<td style="border-top-style:solid;border-top-width:1pt;border-left-style:solid;border-left-width:1pt;border-bottom-style:solid;border-bottom-width:0pt;border-right-style:solid;border-right-width:1pt" colspan="1">';
          xml += '<p class="s5" style="padding-top: 10pt;padding-left: 2pt;text-indent: 0pt;text-align: left;">' + vgmMethod +'</p>';
          xml += '</td>';
          xml += '</tr>';
          xml += '<tr style="width=100%;height:17pt">';
          xml += '<td style="background-color: lightgrey;border-top-style:solid;border-top-width:1pt;border-left-style:solid;border-left-width:1pt;border-bottom-style:solid;border-bottom-width:0pt;border-right-style:solid;border-right-width:0pt" colspan="1">';
          xml += '<p class="s4" style="padding-top: 2pt;padding-left: 5pt;text-indent: 0pt;text-align: left;">Weight UOM (unit of measure)</p>';
          xml += '</td>';
          xml += '<td style="border-top-style:solid;border-top-width:1pt;border-left-style:solid;border-left-width:1pt;border-bottom-style:solid;border-bottom-width:0pt;border-right-style:solid;border-right-width:1pt" colspan="1">';
          xml += '<p class="s5" style="padding-top: 2pt;padding-left: 2pt;text-indent: 0pt;text-align: left;">' + weightUOM +'</p>';
          xml += '</td>';
          xml += '</tr>';
          xml += '<tr style="width=100%;height:12pt">';
          xml += '<td style="background-color: lightgrey;border-top-style:solid;border-top-width:1pt;border-left-style:solid;border-left-width:1pt;border-bottom-style:solid;border-bottom-width:0pt;border-right-style:solid;border-right-width:0pt" colspan="1">';
          xml += '<p class="s4" style="padding-top: 2pt;padding-left: 5pt;text-indent: 0pt;text-align: left;">Container Number (for FCL only)</p>';
          xml += '</td>';
          xml += '<td style="background-color: lightgrey;border-top-style:solid;border-top-width:1pt;border-left-style:solid;border-left-width:1pt;border-bottom-style:solid;border-bottom-width:0pt;border-right-style:solid;border-right-width:1pt" colspan="1">';
          xml += '<p class="s5" style="padding-top: 2pt;padding-left: 2pt;text-indent: 0pt;text-align: left;">Weight</p>';
          xml += '</td>';
          xml += '</tr>';
          xml += '<tr style="width=100%;height:15pt">';
          xml += '<td style="border-top-style:solid;border-top-width:1pt;border-left-style:solid;border-left-width:1pt;border-bottom-style:solid;border-bottom-width:0pt;border-right-style:solid;border-right-width:0pt" colspan="1">';
          xml += '<p class="s4" style="padding-top: 2pt;padding-left: 5pt;text-indent: 0pt;text-align: left;"></p>';
          xml += '</td>';
          xml += '<td style="border-top-style:solid;border-top-width:1pt;border-left-style:solid;border-left-width:1pt;border-bottom-style:solid;border-bottom-width:0pt;border-right-style:solid;border-right-width:1pt" colspan="1">';
          xml += '<p class="s5" style="padding-top: 2pt;padding-left: 2pt;text-indent: 0pt;text-align: left;"></p>';
          xml += '</td>';
          xml += '</tr>';
          xml += '<tr style="width=100%;height:15pt">';
          xml += '<td style="border-top-style:solid;border-top-width:1pt;border-left-style:solid;border-left-width:1pt;border-bottom-style:solid;border-bottom-width:0pt;border-right-style:solid;border-right-width:0pt" colspan="1">';
          xml += '<p class="s4" style="padding-top: 2pt;padding-left: 5pt;text-indent: 0pt;text-align: left;"></p>';
          xml += '</td>';
          xml += '<td style="border-top-style:solid;border-top-width:1pt;border-left-style:solid;border-left-width:1pt;border-bottom-style:solid;border-bottom-width:0pt;border-right-style:solid;border-right-width:1pt" colspan="1">';
          xml += '<p class="s5" style="padding-top: 2pt;padding-left: 2pt;text-indent: 0pt;text-align: left;"></p>';
          xml += '</td>';
          xml += '</tr>';
          xml += '<tr style="width=100%;height:15pt">';
          xml += '<td style="border-top-style:solid;border-top-width:1pt;border-left-style:solid;border-left-width:1pt;border-bottom-style:solid;border-bottom-width:0pt;border-right-style:solid;border-right-width:0pt" colspan="1">';
          xml += '<p class="s4" style="padding-top: 2pt;padding-left: 5pt;text-indent: 0pt;text-align: left;"></p>';
          xml += '</td>';
          xml += '<td style="border-top-style:solid;border-top-width:1pt;border-left-style:solid;border-left-width:1pt;border-bottom-style:solid;border-bottom-width:0pt;border-right-style:solid;border-right-width:1pt" colspan="1">';
          xml += '<p class="s5" style="padding-top: 2pt;padding-left: 2pt;text-indent: 0pt;text-align: left;"></p>';
          xml += '</td>';
          xml += '</tr>';
          xml += '<tr style="width=100%;height:15pt">';
          xml += '<td style="border-top-style:solid;border-top-width:1pt;border-left-style:solid;border-left-width:1pt;border-bottom-style:solid;border-bottom-width:0pt;border-right-style:solid;border-right-width:0pt" colspan="1">';
          xml += '<p class="s4" style="padding-top: 2pt;padding-left: 5pt;text-indent: 0pt;text-align: left;"></p>';
          xml += '</td>';
          xml += '<td style="border-top-style:solid;border-top-width:1pt;border-left-style:solid;border-left-width:1pt;border-bottom-style:solid;border-bottom-width:0pt;border-right-style:solid;border-right-width:1pt" colspan="1">';
          xml += '<p class="s5" style="padding-top: 2pt;padding-left: 2pt;text-indent: 0pt;text-align: left;"></p>';
          xml += '</td>';
          xml += '</tr>';
          xml += '<tr style="width=100%;height:15pt">';
          xml += '<td style="border-top-style:solid;border-top-width:1pt;border-left-style:solid;border-left-width:1pt;border-bottom-style:solid;border-bottom-width:0pt;border-right-style:solid;border-right-width:0pt" colspan="1">';
          xml += '<p class="s4" style="padding-top: 2pt;padding-left: 5pt;text-indent: 0pt;text-align: left;"></p>';
          xml += '</td>';
          xml += '<td style="border-top-style:solid;border-top-width:1pt;border-left-style:solid;border-left-width:1pt;border-bottom-style:solid;border-bottom-width:0pt;border-right-style:solid;border-right-width:1pt" colspan="1">';
          xml += '<p class="s5" style="padding-top: 2pt;padding-left: 2pt;text-indent: 0pt;text-align: left;"></p>';
          xml += '</td>';
          xml += '</tr>';
          xml += '<tr style="width=100%;height:15pt">';
          xml += '<td style="border-top-style:solid;border-top-width:1pt;border-left-style:solid;border-left-width:1pt;border-bottom-style:solid;border-bottom-width:0pt;border-right-style:solid;border-right-width:0pt" colspan="1">';
          xml += '<p class="s4" style="padding-top: 2pt;padding-left: 5pt;text-indent: 0pt;text-align: left;"></p>';
          xml += '</td>';
          xml += '<td style="border-top-style:solid;border-top-width:1pt;border-left-style:solid;border-left-width:1pt;border-bottom-style:solid;border-bottom-width:0pt;border-right-style:solid;border-right-width:1pt" colspan="1">';
          xml += '<p class="s5" style="padding-top: 2pt;padding-left: 2pt;text-indent: 0pt;text-align: left;"></p>';
          xml += '</td>';
          xml += '</tr>';
          xml += '<tr style="width=100%;height:15pt">';
          xml += '<td style="border-top-style:solid;border-top-width:1pt;border-left-style:solid;border-left-width:1pt;border-bottom-style:solid;border-bottom-width:0pt;border-right-style:solid;border-right-width:0pt" colspan="1">';
          xml += '<p class="s4" style="padding-top: 2pt;padding-left: 5pt;text-indent: 0pt;text-align: left;"></p>';
          xml += '</td>';
          xml += '<td style="border-top-style:solid;border-top-width:1pt;border-left-style:solid;border-left-width:1pt;border-bottom-style:solid;border-bottom-width:0pt;border-right-style:solid;border-right-width:1pt" colspan="1">';
          xml += '<p class="s5" style="padding-top: 2pt;padding-left: 2pt;text-indent: 0pt;text-align: left;"></p>';
          xml += '</td>';
          xml += '</tr>';
          xml += '<tr style="width=100%;height:15pt">';
          xml += '<td style="border-top-style:solid;border-top-width:1pt;border-left-style:solid;border-left-width:1pt;border-bottom-style:solid;border-bottom-width:0pt;border-right-style:solid;border-right-width:0pt" colspan="1">';
          xml += '<p class="s4" style="padding-top: 2pt;padding-left: 5pt;text-indent: 0pt;text-align: left;"></p>';
          xml += '</td>';
          xml += '<td style="border-top-style:solid;border-top-width:1pt;border-left-style:solid;border-left-width:1pt;border-bottom-style:solid;border-bottom-width:0pt;border-right-style:solid;border-right-width:1pt" colspan="1">';
          xml += '<p class="s5" style="padding-top: 2pt;padding-left: 2pt;text-indent: 0pt;text-align: left;"></p>';
          xml += '</td>';
          xml += '</tr>';
          xml += '<tr style="width=100%;height:15pt">';
          xml += '<td style="border-top-style:solid;border-top-width:1pt;border-left-style:solid;border-left-width:1pt;border-bottom-style:solid;border-bottom-width:0pt;border-right-style:solid;border-right-width:0pt" colspan="1">';
          xml += '<p class="s4" style="padding-top: 2pt;padding-left: 5pt;text-indent: 0pt;text-align: left;"></p>';
          xml += '</td>';
          xml += '<td style="border-top-style:solid;border-top-width:1pt;border-left-style:solid;border-left-width:1pt;border-bottom-style:solid;border-bottom-width:0pt;border-right-style:solid;border-right-width:1pt" colspan="1">';
          xml += '<p class="s5" style="padding-top: 2pt;padding-left: 2pt;text-indent: 0pt;text-align: left;"></p>';
          xml += '</td>';
          xml += '</tr>';
          xml += '<tr style="width=100%;height:15pt">';
          xml += '<td style="border-top-style:solid;border-top-width:1pt;border-left-style:solid;border-left-width:1pt;border-bottom-style:solid;border-bottom-width:1pt;border-right-style:solid;border-right-width:0pt" colspan="1">';
          xml += '<p class="s4" style="padding-top: 2pt;padding-left: 5pt;text-indent: 0pt;text-align: left;"></p>';
          xml += '</td>';
          xml += '<td style="border-top-style:solid;border-top-width:1pt;border-left-style:solid;border-left-width:1pt;border-bottom-style:solid;border-bottom-width:1pt;border-right-style:solid;border-right-width:1pt" colspan="1">';
          xml += '<p class="s5" style="padding-top: 2pt;padding-left: 2pt;text-indent: 0pt;text-align: left;"></p>';
          xml += '</td>';
          xml += '</tr>';
          xml += '<tr>';
          xml += '<td  colspan="2">';
          xml += '<p class="s7">Upon completion of container loading, please send this fully completed form back to the Forwarding Company representative, before the advised VGM cut-off date and time.</p>';
          xml += '<p class="s7"><br /></p>';
          xml += '<p class="s7"><br /></p>';
          xml += '<p class="s7">I hereby declare that I am an authorized signatory of Shipper and that the information is true and correct for each individual container mentioned above. Shipper shall indemnify Forwarding Company against all loss, damage or expense resulting from the inaccuracy or inadequacy of the above information.</p>';
          xml += '<p class="s7"><br /></p>';
          xml += '<p class="s7">'+empText+'</p>';
          xml += '<p class="s7"><br /></p>';
          xml += '<p class="s7"><br /></p>';
          xml += '<p class="s7">For more information, please refer to the IMO Guidelines on SOLAS.</p>';
          xml += '</td></tr>';
          xml += '</table>';

          /*xml += '<table width="500" style="border-collapse:collapse;margin-left:6.00pt" cellspacing="0">';
          xml += '<tr  style="width=100%;height:72pt">';
          xml += '<td style="background-color: lightgrey;border-top-style:solid;border-top-width:1pt;border-left-style:solid;border-left-width:1pt;border-bottom-style:solid;border-bottom-width:0pt;border-right-style:solid;border-right-width:0pt" colspan="2">';
          xml += '<p class="s2" style="padding-top: 0pt;padding-left: 5pt;text-indent: 0pt;text-align: left;">Shipper Information:</p>';
          xml += '<p class="s2" style="padding-top: 0pt;padding-left: 5pt;text-indent: 0pt;text-align: left;">Company Name</p>';
          xml += '<p class="s2" style="padding-top: 0pt;padding-left: 5pt;text-indent: 0pt;text-align: left;">Authorized Personnel Name</p>';
          xml += '<p class="s2" style="padding-top: 0pt;padding-left: 5pt;text-indent: 0pt;text-align: left;">Contact Phone</p>';
          xml += '<p class="s2" style="padding-top: 0pt;padding-left: 5pt;text-indent: 0pt;text-align: left;">Contact Email</p>';
          xml += '<p class="s2" style="padding-top: 0pt;padding-left: 5pt;text-indent: 0pt;text-align: left;">' + shipperCountry + '</p>';
          xml += '</td>';
          xml += '<td style="border-top-style:solid;border-top-width:1pt;border-left-style:solid;border-left-width:1pt;border-bottom-style:solid;border-bottom-width:0pt;border-right-style:solid;border-right-width:1pt" colspan="2">';
          xml += '<p class="s2" style="padding-top: 0pt;padding-left: 5pt;text-indent: 0pt;text-align: left;">Pliteq, Inc.</p>';
          xml += '<p class="s2" style="padding-top: 0pt;padding-left: 5pt;text-indent: 0pt;text-align: left;">' + owner + '</p>';
          xml += '<p class="s2" style="padding-top: 0pt;padding-left: 5pt;text-indent: 0pt;text-align: left;">416-775-5380</p>';
          xml += '<p class="s2" style="padding-top: 0pt;padding-left: 5pt;text-indent: 0pt;text-align: left;">' + consigneeAddr2 + '</p>';
          xml += '<p class="s2" style="padding-top: 0pt;padding-left: 5pt;text-indent: 0pt;text-align: left;">' + consigneeCity + ', ' + consigneeState + ' ' + consigneeZip + '</p>';
          xml += '<p class="s2" style="padding-top: 0pt;padding-left: 5pt;text-indent: 0pt;text-align: left;">' + consigneeCountry + '</p>';
          xml += '</td>';
          xml += '</tr>';
          xml += '<tr style="height:60pt">';
          xml += '<td style="border-top-style:solid;border-top-width:1pt;border-left-style:solid;border-left-width:1pt;border-bottom-style:solid;border-bottom-width:0pt;border-right-style:solid;border-right-width:0pt" colspan="2">';
          xml += '<p class="s3" style="padding-top: 0pt;padding-left: 5pt;text-indent: 0pt;text-align: left;">Notify Party:</p>';
          xml += '<p class="s2" style="padding-top: 0pt;padding-left: 5pt;text-indent: 0pt;text-align: left;">' + 'Pliteq Building Materials Trading LLC' + '</p>';
          xml += '<p class="s2" style="padding-top: 0pt;padding-left: 5pt;text-indent: 0pt;text-align: left;">' + 'PO Box 473512' + '</p>';
          xml += '<p class="s2" style="padding-top: 0pt;padding-left: 5pt;text-indent: 0pt;text-align: left;">' + 'Dubai - U.A.E.' + '</p>';
          xml += '<p class="s2" style="padding-top: 0pt;padding-left: 5pt;text-indent: 0pt;text-align: left;">' + 'TEL: 0097148135501' + '</p>';
          xml += '<p class="s2" style="padding-top: 0pt;padding-left: 5pt;text-indent: 0pt;text-align: left;">' + 'MOB: 00971554125038' + '</p>';
          xml += '</td>';
          //xml += '</tr>';
          //xml += '<tr style="width=100%;height:17pt">';
          xml += '<td style="border-top-style:solid;border-top-width:1pt;border-left-style:solid;border-left-width:1pt;border-bottom-style:solid;border-bottom-width:0pt;border-right-style:solid;border-right-width:1pt" colspan="2">';
          xml += '<p class="s2" style="padding-top: 2pt;padding-left: 5pt;text-indent: 0pt;text-align: left;"><b>Reference Information</b></p>';
          xml += '<p class="s2" style="padding-top: 2pt;padding-left: 5pt;text-indent: 0pt;text-align: left;">Commerical Invoice Number # <b>' + recNumTrimmed +'</b></p>';
          xml += '<p class="s2" style="padding-top: 2pt;padding-left: 5pt;text-indent: 0pt;text-align: left;">Booking # <b>' + bookingNum +'</b></p>';
          xml += '<p class="s2" style="padding-top: 2pt;padding-left: 5pt;text-indent: 0pt;text-align: left;">Country of Origin: <b>' + shipperCountry +'</b></p>';
          xml += '</td>';
          xml += '</tr>';
          xml += '<tr style="height:25pt">';
          xml += '<td style="border-top-style:solid;border-top-width:1pt;border-left-style:solid;border-left-width:1pt;border-bottom-style:solid;border-bottom-width:0pt;border-right-style:solid;border-right-width:1pt" colspan="4">';
          xml += '<br />';
          xml += '<p class="s3" style="padding-left: 5pt;text-indent: 0pt;line-height: 7pt;text-align: left;">Number of Packages:  ' + totLPic + ' pallets </p>';
          xml += '<br />';
          xml += '<p class="s3" style="padding-left: 5pt;text-indent: 0pt;line-height: 7pt;text-align: left;">Net Weight:  ' + totWeight + ' lbs or ' + totWeightkg + ' kgs</p>';
          xml += '<br />';
          xml += '<p class="s3" style="padding-left: 5pt;text-indent: 0pt;line-height: 7pt;text-align: left;">Gross Weight:  ' + totWeight + ' lbs or ' + totWeightkg + ' kgs</p>';
          xml += '<br />';
          xml += '<br />';
          xml += '</td>';
          xml += '</tr>';
          xml += '</table>'
          xml += '<table width="500" style="border-collapse:collapse;margin-left:6.00pt" cellspacing="0">'
          xml += '<tr style="height:20pt">';
          xml += '<td style="border-top-style:solid;border-top-width:.5pt;border-left-style:solid;border-left-width:.5pt;border-bottom-style:solid;border-bottom-width:.5pt;border-right-style:solid;border-right-width:.5pt" colspan="1">';
          xml += '<p class="s2" style="padding-top: 2pt;padding-left: 2pt;text-indent: 0pt;text-align: left;">Description</p>';
          xml += '</td>';
          xml += '<td style="border-top-style:solid;border-top-width:.5pt;border-left-style:solid;border-left-width:.5pt;border-bottom-style:solid;border-bottom-width:.5pt;border-right-style:solid;border-right-width:.5pt" colspan="1">';
          xml += '<p class="s2" style="padding-top: 2pt;padding-left: 10pt;text-indent: 0pt;text-align: right;">Quantity</p>';
          xml += '</td>';
          xml += '<td style="border-top-style:solid;border-top-width:.5pt;border-left-style:solid;border-left-width:.5pt;border-bottom-style:solid;border-bottom-width:.5pt;border-right-style:solid;border-right-width:.5pt" colspan="1">';
          xml += '<p class="s2" style="padding-top: 2pt;padding-left: 10pt;text-indent: 0pt;text-align: right;">US$ Price</p>';
          xml += '</td>';
          xml += '<td style="border-top-style:solid;border-top-width:.5pt;border-left-style:solid;border-left-width:.5pt;border-bottom-style:solid;border-bottom-width:.5pt;border-right-style:solid;border-right-width:.5pt" colspan="1">';
          xml += '<p class="s2" style="padding-top: 2pt;padding-left: 5pt;text-indent: 0pt;text-align: right;">US$ Value</p>';
          xml += '</td>';
          xml += '</tr>';
          xml += items;
          xml += '<tr style="height:19pt">';
          xml += '<td style="border-top-style:solid;border-top-width:.5pt;border-left-style:solid;border-left-width:.5pt;border-bottom-style:solid;border-bottom-width:.5pt;border-right-style:solid;border-right-width:.5pt" colspan="3">';
          xml += '<p class="s12" style="padding-top: 2pt;padding-left: 300pt;text-indent: 0pt;text-align: right;">INVOICE TOTAL</p>';
          xml += '</td>';
          xml += '<td align="right" style="border-top-style:solid;border-top-width:.5pt;border-left-style:solid;border-left-width:.5pt;border-bottom-style:solid;border-bottom-width:.5pt;border-right-style:solid;border-right-width:.5pt" colspan="1">';
          xml += '<p class="s12" style="padding-top: 2pt;padding-left: 2pt">USD $' + AddCommas(Math.round(totAmount)) + '</p>';
          xml += '</td>';
          xml += '</tr>';
          xml += '</table>'
          xml += '<table width="500" style="border-collapse:collapse;margin-left:6.00pt" cellspacing="0">'
          xml += '<tr style="height:31pt">';
          xml += '<td>';
          xml += '<p class="s3" style="padding-top: 1pt;padding-left: 4pt;text-indent: 0pt;text-align: left;">Special Instructions</p>';
          xml += '<p class="s2" style="padding-top: 1pt;padding-left: 4pt;text-indent: 0pt;text-align: left;">' + customsInstructions + '</p>';
          xml += '</td>';
          xml += '</tr>';
          xml += '</table>'
          xml += '<table width="500" style="border-collapse:collapse;margin-left:6.00pt" cellspacing="0">'
          xml += '<tr style="height:31pt">';
          xml += '<td>';
          xml += '<p class="s3">Description of Goods</p>';
          xml += '<p class="s2">Sound Isolation Materials</p>';
          xml += '<br />';
          xml += '<p class="s2">These commodities are exported from CAN in accordance with the Export Administration Regulations. Diversion contrary to CAN Law is probibited.</p>';
          xml += '<br />';
          xml += '<br />';
          xml += '<br />';
          xml += '<p class="s14">I hereby declare that the information on this invoice is true and correct.</p>';
          xml += '<p class="s14">Nav Kaur, Manager</p>';
          xml += '<p class="s14">Inventory/Supply Chain Customer Relations</p>';
          xml += '<br />';
          xml += '<br />';
          xml += '<p class="s16">T:416.449.0049 F:416.849.0415 - Royal Group Cresent, Vaughn, ON L4H 1X9</p>';
          xml += '<p class="s16">www.pliteq.com</p>';
          xml += '</td>';
          xml += '</tr>';
          xml += '</table>';*/
          xml += '</body>';
          xml += '</pdf>';

          //end of ttemplate begining of render
            var file = nlapiXMLToPDF(xml);
            var contents = file.getValue();
            var renderer = nlapiCreateTemplateRenderer(contents);
            renderer.setTemplate(contents);
            var renderPDF = renderer.renderToString();
            response.setContentType('PDF', recNum + '.pdf', 'inline');
            response.write(renderPDF);
            nlapiLogExecution('DEBUG', 'PDF Rendered', 'Intl Commercial Invoice was rendered!');
        } catch (err) {
            nlapiLogExecution('DEBUG', 'Error Caught', 'Error is ' + err);
        }
    } // JavaScript source code
}
function AddCommas(nStr) {
   nStr += '';
   var x = nStr.split('.');
   var x1 = x[0];
   var x2 = x.length > 1 ? '.' + x[1] : '';
   var rgx = /(\d+)(\d{3})/;
   while (rgx.test(x1)) {
       x1 = x1.replace(rgx, '$1' + ',' + '$2');
   }
   return x1 + x2;
}
